version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=testeliveuser
      - POSTGRES_PASSWORD=testlivepass
      - POSTGRES_DB=testlivedb
    ports:
      - "5432:5432"
    restart: always
    networks:
      - custom

networks:
    custom:
      driver: bridge